MODEL:
  TYPE: swin_mamba
  NAME: swin_mamba_luna16
  NUM_CLASSES: 2          # 改成你的类别数
  DROP_PATH_RATE: 0.1
  SWIN_MAMBA:
    PATCH_SIZE: 4
    IN_CHANS: 3           # 若原图是灰度，设为1；若已是RGB则设为3
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 16
    MLP_RATIO: 4.0
    PATCH_NORM: True
    FUSED_WINDOW_PROCESS: False
    D_STATE: 8
    RMS_NORM: True

DATA:
  DATASET: imagenet        # 文件夹分类格式
  DATA_PATH: /root/autodl-fs/two_yolo_swinmamba
  IMG_SIZE: 512            # 根据你的图像分辨率可调
  BATCH_SIZE: 32
  INTERPOLATION: bicubic

TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  BASE_LR: 5e-4
  WARMUP_LR: 5e-7
  MIN_LR: 5e-6
  ACCUMULATION_STEPS: 1
  CLIP_GRAD: 1.0   # 也可以顺便把梯度裁剪得更严一点
  AUTO_RESUME: false

AUG:
  MIXUP: 0.0               # 医学场景可先关掉
  CUTMIX: 0.0
  AUTO_AUGMENT: none
  COLOR_JITTER: 0.0
TEST:
  CROP: false
SAVE_FREQ: 10
PRINT_FREQ: 50
SEED: 0